# Generated by Django 2.1.1 on 2019-02-02 12:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_wiki',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
