# Generated by Django 2.1.1 on 2019-01-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
