# Generated by Django 2.1.1 on 2019-01-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_sale_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='price_in_cents',
        ),
    ]
