# Generated by Django 2.1.1 on 2019-01-13 22:47

import datetimeutc.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20190112_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='submitted',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
