# Generated by Django 2.1.1 on 2019-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_saleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
