# Generated by Django 2.1.1 on 2019-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_saleproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saleproduct',
            old_name='charge_id',
            new_name='sale',
        ),
        migrations.AlterField(
            model_name='sale',
            name='charge_id',
            field=models.CharField(max_length=128),
        ),
    ]
