# Generated by Django 2.1.1 on 2018-12-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvote',
            options={'managed': True},
        ),
    ]
