# Generated by Django 2.1.2 on 2018-11-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductArea'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_complexity',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_need',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
    ]
