# Generated by Django 2.1.1 on 2018-12-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181221_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvote',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductVote',
        ),
    ]
