# Generated by Django 2.1.2 on 2018-11-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181111_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_complexity',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_need',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1),
        ),
    ]
