# Generated by Django 2.1.2 on 2018-11-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181111_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_payment',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_complexity',
            field=models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH')], max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_need',
            field=models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH')], max_length=6),
        ),
    ]
