# Generated by Django 2.1.2 on 2018-11-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181111_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='payment',
            new_name='price',
        ),
    ]
