# Generated by Django 2.1.1 on 2018-12-30 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvote_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
