# Generated by Django 2.1.1 on 2018-12-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_area',
        ),
        migrations.RemoveField(
            model_name='productvote',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductVote',
        ),
    ]
