# Generated by Django 2.1.2 on 2018-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181117_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_document',
            field=models.FileField(upload_to='product_documents'),
        ),
    ]
