# Generated by Django 2.1.1 on 2018-12-30 23:46

import datetimeutc.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181230_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product_need', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('product_complexity', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('status', models.CharField(choices=[('T', 'To Do'), ('D', 'Doing'), ('C', 'Complete')], max_length=1)),
                ('product_type', models.CharField(choices=[('I', 'Issue'), ('F', 'Feature')], max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('product_document', models.FileField(blank=True, upload_to='product_documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])])),
                ('product_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductArea')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('submitted', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
