# Generated by Django 2.1.5 on 2019-02-05 13:14

import datetimeutc.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_productvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTimeAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('time_minutes', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254, validators=[django.core.validators.RegexValidator(message='Name can only have letters, Numbers and Spaces', regex='[\\w\\s\\d]+')]),
        ),
        migrations.AddField(
            model_name='producttimeassigned',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
