# Generated by Django 2.1.5 on 2019-02-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190205_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producttimeassigned',
            name='time_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
