# Generated by Django 2.1.2 on 2018-11-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181119_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_complexity',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_need',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], max_length=1),
        ),
    ]
