# Generated by Django 2.1.5 on 2019-02-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190205_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_time',
        ),
    ]
