# Generated by Django 2.1.2 on 2018-11-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181119_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
