# Generated by Django 2.1.2 on 2018-12-10 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181125_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_document',
            field=models.FileField(blank=True, upload_to='product_documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])]),
        ),
    ]
